name: Run Cypress Tests

on:
  schedule:
    - cron: '0 20 * * *'

  push:
    branches: [ master ]

  workflow_dispatch:
    inputs:
      cli:
        description: Run by cypress command line
        default:  npx cypress run

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false # https://github.com/cypress-io/github-action/issues/48
      matrix:
        node-version: [ 22.x ] # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm i

      - name: Run Cypress Tests
        run: |
          npx cypress run \
            --record \
            --key f8731af1-8aba-4a37-bdb7-a07710e4b1c7

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ./test-results
